### ISSUE TITLE
Missing body fields in signature api

### ISSUE THREAD

**Issue by nithiz** [ActiveCampaign/postmark-php#103]
Hi,

I'm trying to use a custom message when creating a signature as described here https://postmarkapp.com/developer/api/signatures-api#create-signature.

The field is ConfirmationPersonalNote, but this field is missing from the PHP library. Is there any way to still customize this message?

Thanks!

**Comment by ewood-ac** [comment]
Hopefully you have already found a solution. I see this field used in the unit tests as one of the parameters. I am going to close this issue. If you are still having issues please feel free to open it again. However, can you be more specific about what call you are making and the response payload you are seeing?
