### ISSUE TITLE
New line breaks not converted when forcing send as HTML

### ISSUE THREAD

**Issue by davelozier** [ActiveCampaign/postmark-php#108]
When the content type is text/plain and we're forcing send as HTML it would greatly help readability if new line breaks \n were converted to <br> tags.

This fix seems to work, in wp-mail.php:

Change
```
	if ( 1 === (int) $settings['force_html'] || 'text/html' === $content_type || 1 === $track_opens ) {
		$body['HtmlBody'] = $message;
		// The user really, truly wants this sent as HTML, don't send it as text, too.
		// For historical reasons, we can't "force html" and "track opens" set both html and text bodies,
		// which is incorrect, but in order not to break existing behavior, we only strip out the textbody when
		// the user has gone to the trouble of specifying content type of 'text/html' in their headers.
		if ( 'text/html' === $content_type ) {
			unset( $body['TextBody'] );
		}
	}
```

To
```
	if ( 1 === (int) $settings['force_html'] || 'text/html' === $content_type || 1 === $track_opens ) {
                if ( 'text/plain' === $content_type ) {
                        $message = str_replace( "\n", "<br>", $message );
                }
		$body['HtmlBody'] = $message;
		// The user really, truly wants this sent as HTML, don't send it as text, too.
		// For historical reasons, we can't "force html" and "track opens" set both html and text bodies,
		// which is incorrect, but in order not to break existing behavior, we only strip out the textbody when
		// the user has gone to the trouble of specifying content type of 'text/html' in their headers.
		if ( 'text/html' === $content_type ) {
			unset( $body['TextBody'] );
		}
	}
```

**Comment by ewood-ac** [comment]
Can you explain this a bit more? I am not sure I fully understand the issue you are describing. The fix you put in place appears to be WordPress is there a meaningful change for Postmark here?

**Comment by davelozier** [comment]
Sorry - I think I confused this with the postmark wordpress plugin which this fix pertains to.  For clarity this fix is related to text only emails that are forced sent as HTML. In these cases new line breaks in the text only message are ignored and the message is displayed as one long text string. Replacing the line breaks with <br> tags when the content type was text/plain to start makes the message more readable since everything isn't in one long string.

I hoped that helped. Cheers!

**Comment by ewood-ac** [comment]
Thanks - I put in an MR for this change. Closing this issue since it's a different repo.

**Comment by pgraham3** [comment]
Thanks for the [WP plugin PR](https://github.com/ActiveCampaign/postmark-wordpress/pull/107) @ewood-ac! Will take a look this week @davelozier
