### ISSUE TITLE
[5.0.1] Introduces breaking changes with return types ☠️

### ISSUE THREAD

**Issue by wallacio** [ActiveCampaign/postmark-php#115]
After updating from 5.0 to 5.0.1, I notice that return types of some methods have changed. This has broken bits of our application. I'm happy that there's progress finally being made here but can we please have this kind of information mentioned in release notes?

For example, the method `PostmarkAdminClient::getServer()` now returns a type of PostmarkServer, where previously it returned the ubiquitous `DynamicResponseModel`
https://github.com/ActiveCampaign/postmark-php/blob/c7a437163d8de45938546cabfca7df61988bb0e6/src/Postmark/PostmarkAdminClient.php#L44

This applies to many of the methods in the Admin Client (methods that return `PostmarkDomainDetails`, for example). I haven't fully looked through all these changes but it's caused us an unexpected headache, refactoring our strictly typed code. 

Is `DynamicResponseModel` being dropped completely? I'm no fan of it at all so I'll be glad to see it gone, but a heads-up on these changes in what looked to be a minor/patch release would have been appreciated.

Additionally, the signatures of the WebhookConfiguration* constructors have changed, and some renamed (`WebhookConfigurationSubscriptionChange` to `WebhookConfigurationSubscriptionChangeTrigger`).

We've upgraded to 5.0.1 to be able to use the `verifyDKIM` and `verifyReturnPath` methods, but we can't have these without these other breaking changes!

**Comment by ewood-ac** [comment]
This is my fault for sure. I tagged the releases in a confusing way sorry about that.

Yes, we are working our way towards dropping several of the dynamic types. I will try to be more clear about what is in the releases.
