### ISSUE TITLE
Messagestream wrongly described

### ISSUE THREAD

**Issue by piegus** [ActiveCampaign/postmark-php#118]
When phpstan run through my code it gave me error due to bad docs:
```
Parameter $messageStream of method Postmark\PostmarkClient::sendEmailWithTemplate() expects array|null, string|null given
```

This is how I use your template:
![image](https://github.com/ActiveCampaign/postmark-php/assets/984152/cc54ee22-fa86-43f3-bb4c-02abe9484594)

my Mail::getMessageStream looks like:
```
    public function getMessageStream():?string
    {
        return $this->messageStream;
    }
```

`\Postmark\PostmarkClient::sendEmailWithTemplate`

```	 * @param  array $messageStream  The message stream used to send this message. If not provided, the default transactional stream "outbound" will be used.
```

When in postmark application I see that 

![image](https://github.com/ActiveCampaign/postmark-php/assets/984152/2bb2785d-b2d8-400d-8629-c883cb279ecf)

I think that documentation should'd be changed to:
```	 * @param  string|null $messageStream  The message stream used to send this message. If not provided, the default transactional stream "outbound" will be used.
```

**Comment by ewood-ac** [comment]
I have fixed this in the next release. Thanks for bringing it to our attention.
