### ISSUE TITLE
`Postmark\Models\Stats\PostmarkOutboundEmailClientStats` does not comply with psr-0

### ISSUE THREAD

**Issue by manavo** [ActiveCampaign/postmark-php#121]
Hi team,

I just noticed that when installing the latest version of the SDK (`v6.0.1` at this point in time) I get this warning when running `composer install`:

```Class Postmark\Models\Stats\PostmarkOutboundEmailClientStats located in ./vendor/wildbit/postmark-php/src/Postmark/Models/Stats/PostmarkOutboundClientStats.php does not comply with psr-0 autoloading standard. Skipping.```

Composer doesn't fail, but guessing that class might not work if someone needed it? (I don't use it, so doesn't impact me)

(Tested with composer versions: `2.5.4` and `2.6.6`)

Thanks!

**Comment by ewood-ac** [comment]
I appreciate you bringing this to my attention.
Those 2 files should have been removed - they are basically empty. It will be addressed in v6.0.2

**Comment by manavo** [comment]
Ha, was reporting this in a rush and didn't even look at the files to see they're empty. Glad it's an easy fix at least! 🙂

**Comment by ewood-ac** [comment]
v6.0.2 Fixes this.
