### ISSUE TITLE
PostmarkClient@getSuppressions returns PostmarkSuppressionResultList instead of PostmarkSuppressionList

### ISSUE THREAD

**Issue by ashgibson** [ActiveCampaign/postmark-php#125]
As per title. It appears the the PostmarkClient@getSuppressions function is incorrectly returning a PostmarkSuppressionResultList instead of a PostmarkSuppressionList. 

PostmarkSuppressionResultList should be used for the return value of creating suppressions and PostmarkSuppressionList should be used when querying suppressions

Have created pull request - https://github.com/ActiveCampaign/postmark-php/pull/126

**Comment by ewood-ac** [comment]
I have approved this change.

**Comment by ashgibson** [comment]
Can a new release be created with this fix please.

**Comment by ewood-ac** [comment]
Sorry for the delay. I have that out now.
