### ISSUE TITLE
Sending to multiple to addresses with template

### ISSUE THREAD

**Issue by cgsmith** [ActiveCampaign/postmark-php#135]
I could be wrong but it seems like there is no way to call `sendWithTemplate()` with multiple to addresses. Can it be refactored to allow multiple to addresses or is this an API limitation in Postmark?

**Comment by ewood-ac** [comment]
Thanks for the question.
As the API documents say - while the 'To' is a string, it should honor multiple emails that are separated by a comma.
https://postmarkapp.com/developer/api/templates-api#email-with-template

If this is not working please let us know.

**Comment by cgsmith** [comment]
Thanks for clarifying. Is it possible to update the code docs? https://github.com/ActiveCampaign/postmark-php/blob/6a7c57984c043a062a0c27db3e0036ab0d2d256d/src/Postmark/PostmarkClient.php#L215

**Comment by ewood-ac** [comment]
Sure - please feel free to submit a PR with what you think would be a better description there.
