### ISSUE TITLE
Allow array to be passed to to, cc, or bcc fields

### ISSUE THREAD

**Issue by cgsmith** [ActiveCampaign/postmark-php#137]
@ewood-ac - what do you think about a PR that allows either string or array for to, cc, and bcc fields? Would be curious to know your thoughts before making a draft PR an associated tests.

Doing this could also throw an exception when the arrays of to + cc + bcc exceed the 50 maximum addresses.

**Comment by ewood-ac** [comment]
I think that would be a great addition. I will do my best to be responsive and review the code as quickly as I can and turn around a release.

**Comment by cgsmith** [comment]
Excellent! I'll submit a PR in the next day or two.
