### ISSUE TITLE
Update to Wiki with example of array and remove Travis CI calls

### ISSUE THREAD

**Issue by cgsmith** [ActiveCampaign/postmark-php#139]
Relates to issue #138 and provides some updates to the Wiki. Unfortunately wiki's don't allow PRs. I'll add my `.patch` as a `.txt` file because of supported file types as well.
[update_to_sending_email_for_arrays_and_updated_github_markdown_for_notes_and_info_travis_c.txt](https://github.com/user-attachments/files/17310747/update_to_sending_email_for_arrays_and_updated_github_markdown_for_notes_and_info_travis_c.txt)

**Comment by cgsmith** [comment]
To apply the patch:

1. Checkout the wiki `git clone https://github.com/ActiveCampaign/postmark-php.wiki.git`
2. Download .txt file and change to .patch file (might be unnecessary)
3. `git apply update_to_sending_email_for_arrays_and_updated_github_markdown_for_notes_and_info_travis_c.patch`

**Comment by ewood-ac** [comment]
Thanks for this. These changes have been made.
