### ISSUE TITLE
Sending a templated email with an empty model fails

### ISSUE THREAD

**Issue by smilledge** [ActiveCampaign/postmark-php#37]
Calling `sendEmailWithTemplate()` with an empty model (eg `array()`, `null`, etc) fails with a `Received valid, but incompatible JSON input` error.

Would be nice if empty models were removed from the request. The error is kinda misleading as the JSON isn't actually invalid.

At the moment I'm just sending a template model of `array('empty' => '')` to get around the error as there doesn't seem to be a way to send an empty model?

**Comment by ewood-ac** [comment]
Thanks for the feedback - I am going to close this issue due to the age. We are working on making updates and will take this feedback into consideration.
