### ISSUE TITLE
any interest in async behavior?

### ISSUE THREAD

**Issue by netProphET** [ActiveCampaign/postmark-php#47]
I've extended the `PostmarkClient::sendEmail()` and `PostmarkClient::sendEmailWithTemplate()` to work asynchronously in a private project. If there's any interest in this feature, I'd be happy to work on a PR.

**Comment by netcarver** [comment]
@netProphET Hello Mike, I'd be interested in that if even if no one else is.

**Comment by ewood-ac** [comment]
This would be a great thing to submit as an MR. Appreciate the feedback. Closing this issue due to it's age.
