### ISSUE TITLE
[Request] Support for PHP 8.1

### ISSUE THREAD

**Issue by wkhayrattee** [ActiveCampaign/postmark-php#97]
Hello, is there any plan to make the codebase to work with PHP 8.1 on may be v5 soon (any ETA)?
_(Right it's not working)_

Please also note that PHP 7.4 is nearing EOL in 2 month's time (Nov 2022).

**Comment by wkhayrattee** [comment]
Update:
I just read https://github.com/ActiveCampaign/postmark-php/pull/95
I was on v4.0.2, just bumped to v4.0.4 and the suppression seems to work.

Any ETA on when we will have the codebase fully ready for PHP 8.1?

thank you

**Comment by bmdumr** [comment]
This really needs to be addressed. After updating server to php 8.1 due to 7.4 EOL, I'm seeing entry after entry in the php error log showing `PHP Deprecated:  Return type of Postmark\Models\CaseInsensitiveArray`

**Comment by wallacio** [comment]
Right, come on team - where's full support for PHP 8.1 and 8.2, now that 8.0 is imminently EOL too? We've got code that's unable to run in our PHP 8.1 application because of E_ERROR stuff being thrown because of "During inheritance of JsonSerializable: Uncaught Exception" messages relating to the WebhookConfiguration* classes.

**Comment by malles** [comment]
Sending this to postmark customer support, maybe they can direct some attention.

**Comment by ewood-ac** [comment]
I am working on bringing the library up to date. Thanks. Should have it soon.

**Comment by wallacio** [comment]
Thanks for showing some progress with bringing this library up to date.

Is it safe to assume that the 5.x release is a work in progress, in that regard? Whilst I see that various things are moving towards PHP 8,x, many of the type-related issues mentioned in this issue persist.

**Comment by ewood-ac** [comment]
Thanks for the feedback. Yes! I am continuing to work on rolling out some changes. I hope to have some updates to share soon.

**Comment by ewood-ac** [comment]
I'm going to close this issue as we should be releasing v6 soon and much of this should be addressed in that version.
